#!/usr/bin/env python3
"""
mt2_emit_notes.py — emit the ENEMY_NOTES block for gamedata.js from the `note`
column of difficulty_observations.csv. The note is the enemy/boss ability text
shown in the app's hover/click popover over a wave-list name.

Notes are sourced from the *Overgrowth* rows only (the app targets Overgrowth),
keyed by *display name*. A note can vary by order (e.g. Athane Rage 1→2→3), so
the value mirrors ENEMY_STATS/BOSS_STATS: a single string when the note is the
same at every recorded order, or an [O1,O2,O3,O4,O5] array (null per order without a
note) when it differs — the app resolves both via pickByOrder. An Internal with
no Overgrowth note at any order is omitted (fix it in the CSV; no cross-difficulty
fallback). Covers BOTH non-boss enemies and bosses (a boss's note is keyed by its
variant/CSV display name; the app passes that key for the boss span). Notes may
contain <br> for multi-line text; it survives json.dumps as a literal substring
and the app renders it as innerHTML.

Duplicate display names are collapsed like ENEMY_STATS: the non-spawning Internal
is dropped via EXCLUDE_INTERNALS so the surviving note is the enemy you fight.

Usage:  python3 mt2_emit_notes.py [--csv difficulty_observations.csv] [--write gamedata.js]
"""
import sys, os, re, csv, json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mt2_emit_enemy_stats import EXCLUDE_INTERNALS  # reuse the duplicate-name drops

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def render_block(rows):
    lines = [
        '// ---- Per-enemy ability notes (hover/click popover text) ----',
        '// Keyed by display name → ability text (may contain <br> for multi-line).',
        '// Value is a single string when the note is the same at every order, or an',
        '// [O1,O2,O3,O4,O5] array (null per order without a note) when it varies by order',
        '// — same string|array shape as ENEMY_STATS/BOSS_STATS (resolve via pickByOrder).',
        '// Covers enemies AND bosses (boss note keyed by variant/CSV display name).',
        '// OBSERVED, from the Overgrowth rows of difficulty_observations.csv (note',
        '// column). Generated by extraction/mt2_emit_notes.py — edit the CSV.',
        'const ENEMY_NOTES = {',
    ]
    # internal -> {'display': str, 'orders': {order:int -> note}}, Overgrowth only.
    # First non-empty note per order wins; non-spawning duplicates are dropped.
    by_internal = {}
    for r in rows:
        if (r.get('difficulty') or '').strip() != 'Overgrowth':
            continue
        internal = (r.get('internal') or '').strip()
        note = (r.get('note') or '').strip()
        if not internal or internal in EXCLUDE_INTERNALS or not note:
            continue
        try:
            order = int((r.get('order') or '').strip())
        except ValueError:
            continue
        d = by_internal.setdefault(internal, {'display': (r.get('display') or '').strip(), 'orders': {}})
        d['orders'].setdefault(order, note)
    # Collapse to display-name -> string | [O1..O4]; one note per display name.
    entries = {}
    seen = set()
    for internal, d in sorted(by_internal.items()):
        name = d['display']
        if not name or name in seen:
            continue                      # one note per display name
        seen.add(name)
        orders = d['orders']
        if len(set(orders.values())) <= 1:
            entries[name] = next(iter(orders.values()))       # invariant → string
        else:
            entries[name] = [orders.get(o) for o in (1, 2, 3, 4, 5)]  # per-order array
    for name in sorted(entries):
        lines.append(f'    {json.dumps(name)}: {json.dumps(entries[name], ensure_ascii=False)},')
    lines.append('};')
    return '\n'.join(lines)


def main():
    argv = sys.argv[1:]
    csv_path = argv[argv.index('--csv') + 1] if '--csv' in argv else os.path.join(REPO, 'difficulty_observations.csv')
    target = argv[argv.index('--write') + 1] if '--write' in argv else None

    with open(csv_path, newline='') as f:
        rows = list(csv.DictReader(f))
    block = render_block(rows)

    if not target:
        print(block)
        return

    src = open(target).read()
    pat = re.compile(r'(?:^//[^\n]*\n)*const ENEMY_NOTES = \{.*?\n\};',
                     re.DOTALL | re.MULTILINE)
    src, n = pat.subn(lambda _: block, src, count=1)
    if n == 0:
        # First emit: insert just after the ENEMY_STATS block.
        anchor = re.compile(r'(const ENEMY_STATS = \{.*?\n\};\n)', re.DOTALL)
        src, n = anchor.subn(lambda m: m.group(1) + '\n' + block + '\n', src, count=1)
        if n != 1:
            sys.exit(f'ERROR: could not locate ENEMY_STATS anchor in {target}')
    open(target, 'w').write(src)
    print(f'Updated {target}')


if __name__ == '__main__':
    main()
