#!/usr/bin/env python3
"""
mt2_emit_enemy_stats.py — emit the ENEMY_STATS block for gamedata.js from the
hand-maintained observation CSV (default: enemy_observations.csv at repo root).

Unlike BOSS_STATS (computed from the scaling formula), non-boss enemy order
scaling has never been solved (see CLAUDE.md / docs/enemy_scaling.md), so these
values are *observed in-game*, not computed. The CSV is the source of truth and
is edited by hand in Excel.

ENEMY_STATS is keyed by enemy *display name* → ['O1','O2','O3','O4'] of
'ATK⚔️ HP❤️', with null where that order hasn't been observed yet. Duplicate
display names (distinct Internal, e.g. two "Mother's Amalgam") collapse to the
FIRST row in the CSV — the interim rule until the wave data carries internal
identity (CLAUDE.md duplicate-rows TODO).

Usage:  python3 mt2_emit_enemy_stats.py [--csv enemy_observations.csv] [--write gamedata.js]
"""
import sys, os, re, csv, json

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLACEHOLDER = None  # JSON null for an unobserved order


def stat(a, h):
    a, h = (a or '').strip(), (h or '').strip()
    return f'{a}⚔️ {h}❤️' if a and h else PLACEHOLDER


def load_rows(csv_path):
    with open(csv_path, newline='') as f:
        return list(csv.DictReader(f))


def render_block(rows):
    lines = [
        '// ---- Per-enemy observed stats by visit order ----',
        '// Keyed by enemy display name → [O1,O2,O3,O4] of \'ATK⚔️ HP❤️\', null',
        '// where that order has not been observed in-game yet. OBSERVED, not',
        '// computed (non-boss scaling is unsolved). Generated by',
        '// extraction/mt2_emit_enemy_stats.py from enemy_observations.csv —',
        '// edit the CSV (in Excel), not this block.',
        'const ENEMY_STATS = {',
    ]
    seen = set()
    for r in rows:
        name = (r.get('Name') or '').strip()
        if not name or name in seen:
            continue  # first row wins for duplicate display names
        seen.add(name)
        vals = [stat(r.get(f'O{n} ATK'), r.get(f'O{n} HP')) for n in (1, 2, 3, 4)]
        lines.append(f'    {json.dumps(name)}: {json.dumps(vals, ensure_ascii=False)},')
    lines.append('};')
    return '\n'.join(lines)


def main():
    argv = sys.argv[1:]
    csv_path = argv[argv.index('--csv') + 1] if '--csv' in argv else os.path.join(REPO, 'enemy_observations.csv')
    target = argv[argv.index('--write') + 1] if '--write' in argv else None

    block = render_block(load_rows(csv_path))

    if not target:
        print(block)
        return

    src = open(target).read()
    pat = re.compile(r'(?:^//[^\n]*\n)*const ENEMY_STATS = \{.*?\n\};',
                     re.DOTALL | re.MULTILINE)
    src, n = pat.subn(lambda _: block, src, count=1)
    if n == 0:
        # First emit: insert just after the BOSS_STATS block.
        anchor = re.compile(r'(const BOSS_STATS = \{.*?\n\};\n)', re.DOTALL)
        src, n = anchor.subn(lambda m: m.group(1) + '\n' + block + '\n', src, count=1)
        if n != 1:
            sys.exit(f'ERROR: could not locate BOSS_STATS anchor in {target}')
    open(target, 'w').write(src)
    print(f'Updated {target}')


if __name__ == '__main__':
    main()
