#!/usr/bin/env python3
"""
mt2_emit_boss_stats.py — emit the BOSS_STATS block for gamedata.js from the
OBSERVED boss rows of difficulty_observations.csv (now the authoritative stat
source). This replaced the former computed path (roster.json + scaling.json +
the old mt2_build_outputs.compute_orders) — boss ATK/HP is now hand-observed
exactly like enemy stats. (mt2_build_outputs.py, which owned that scaling math,
was retired to deprecated/ on 2026-07-03; nothing imports it anymore.)

BOSS_STATS is keyed by the boss *variant* name shown in the app dropdowns:
  - Main-region + minor "battle" bosses → ['O1','O2','O3','O4'] of 'ATK⚔️ HP❤️'
    (null for an order not yet observed).
  - Astrael (O1 only) and Lifemother (O4 only) → a single 'ATK⚔️ HP❤️' string.

CSV display names are authoritative, so Astrael's row is 'Astrael the First
Reborn' (remapped onto BOTH dropdown keys "Mother's Flagellant"/"Mother's
Hunter" here) and Lifemother's rows are Corpseflower/Swarmhost/Undying Bloom.
TODO: rename the BOSS_STATS keys + app dropdowns to the CSV names and drop the
Astrael remap (then this file keys straight off the CSV display name).

Usage:  python3 mt2_emit_boss_stats.py [--csv difficulty_observations.csv]
                                       [--difficulty Overgrowth] [--write gamedata.js]
"""
import sys, os, re, csv, json

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DEFAULT_CSV = os.path.join(REPO, 'difficulty_observations.csv')

ASTRAEL_INTERNAL = 'Boss_SoulSavior_R0_TrainBoss_Defensive'
LIFEMOTHER_INTERNALS = {
    'Boss_SoulSavior_Final_Lifemother_Debuffer',
    'Boss_SoulSavior_Final_Lifemother_Infested',
    'Boss_SoulSavior_Final_Lifemother_HealReanimate',
}
# Bosses whose BOSS_STATS value is a single string (one fixed order), not [O1..O4].
SINGLE_ORDER_INTERNALS = {ASTRAEL_INTERNAL} | LIFEMOTHER_INTERNALS

# Ordered (comment, [(variant_key, internal_or_None)]) groups — mirrors the app's
# VARIANT_OPTIONS and fixes the emitted key order. internal=None → resolve via the
# CSV display name (which == the variant key for every boss except Astrael, whose
# two dropdown keys both map to the single 'Astrael the First Reborn' CSV row).
GROUPS = [
    ('Astrael (O1 only; both combats are the same Astrael fight)', [
        ("Mother's Flagellant", ASTRAEL_INTERNAL),
        ("Mother's Hunter",     ASTRAEL_INTERNAL)]),
    ('Lifemother (final boss; single fixed stat)', [
        ('Corpseflower', None), ('Swarmhost', None), ('Undying Bloom', None)]),
    ('Maera Battle', [('Athane the Fallen', None), ('Korin the Judged', None)]),
    ('Maera Boss',   [('Stern Sister', None), ('Sibling Hierarchy', None), ('Eldest Scion', None)]),
    ('Thaddeus Battle', [('Elebor the Unstoppable', None), ('Quoto the Destroyer', None)]),
    ('Thaddeus Boss',   [('Train Chomper', None), ('Thick Skinned', None), ('Insatiable', None)]),
    ('Tivi Battle', [('Phalanx', None), ('The Undying Spirit', None)]),
    ('Tivi Boss',   [('Duplicitous', None), ('Mischevious Child', None), ('Prankster', None)]),
    ('Lylith Battle', [('Qel the Malaiser', None), ('Ajax the Deathbringer', None)]),
    ('Lylith Boss',   [('Plaguebringer', None), ('Energy Vampire', None), ('Inoculation', None)]),
]


def load_csv(path, diff):
    """Return (obs, disp2int): obs[internal][order]=(atk,hp) for filled boss rows
    at `diff`; disp2int maps each boss display name -> internal (any difficulty)."""
    obs, disp2int = {}, {}
    for r in csv.DictReader(open(path, newline='')):
        if not r['internal'].startswith('Boss_'):
            continue
        disp2int.setdefault(r['display'], r['internal'])
        if r['difficulty'] != diff:
            continue
        a, h = (r['atk'] or '').strip(), (r['hp'] or '').strip()
        if a and h:
            obs.setdefault(r['internal'], {})[int(r['order'])] = (a, h)
    return obs, disp2int


def stat(cell):
    return None if cell is None else f'{cell[0]}⚔️ {cell[1]}❤️'


def value_for(internal, obs):
    cells = obs.get(internal, {})
    if internal in SINGLE_ORDER_INTERNALS:        # one fixed order (Astrael O1 / Lifemother O4)
        if not cells:
            return None
        return stat(cells[sorted(cells)[0]])
    return [stat(cells.get(o)) for o in (1, 2, 3, 4)]


def render_block(obs, disp2int):
    lines = [
        '// ---- Per-variant observed stats by visit order ----',
        '// Keyed by variant name. Main-region + minor bosses store',
        "// ['O1','O2','O3','O4'] of 'ATK⚔️ HP❤️' (null = order not yet observed);",
        '// Astrael (O1) and Lifemother (final) store a single string. OBSERVED,',
        '// from difficulty_observations.csv (boss rows). Generated by',
        '// extraction/mt2_emit_boss_stats.py — edit that file, not this block.',
        'const BOSS_STATS = {',
    ]
    missing = []
    for comment, entries in GROUPS:
        lines.append(f'    // {comment}')
        for key, internal in entries:
            internal = internal or disp2int.get(key)
            if not internal:
                missing.append(key)
                val = None
            else:
                val = value_for(internal, obs)
            lines.append(f'    {json.dumps(key)}: {json.dumps(val, ensure_ascii=False)},')
    lines.append('};')
    return '\n'.join(lines), missing


def main():
    argv = sys.argv[1:]
    csv_path = argv[argv.index('--csv') + 1] if '--csv' in argv else DEFAULT_CSV
    diff = argv[argv.index('--difficulty') + 1] if '--difficulty' in argv else 'Overgrowth'
    target = argv[argv.index('--write') + 1] if '--write' in argv else None

    obs, disp2int = load_csv(csv_path, diff)
    block, missing = render_block(obs, disp2int)
    if missing:
        print('WARNING: unresolved variants ->', missing, file=sys.stderr)

    if not target:
        print(block)
        return

    src = open(target).read()
    pat = re.compile(r'(?:^//[^\n]*\n)*const BOSS_STATS = \{.*?\n\};',
                     re.DOTALL | re.MULTILINE)
    src, n = pat.subn(lambda _: block, src, count=1)
    if n != 1:
        sys.exit(f'ERROR: could not locate BOSS_STATS block in {target}')
    open(target, 'w').write(src)
    print(f'Updated {target} ({diff} observed boss stats)')


if __name__ == '__main__':
    main()
