#!/usr/bin/env python3
"""
mt2_emit_boss_stats.py — emit the BOSS_STATS block for gamedata.js from
roster.json + scaling.json, reusing mt2_build_outputs.compute_orders so the
scaling math has a single source of truth.

BOSS_STATS is keyed by the boss *variant* name shown in the app dropdowns:
  - Main-region bosses + minor "battle" bosses → order-scaled ['O1','O2','O3','O4']
    of 'ATK⚔️ HP❤️'.
  - Astrael (O1 only) and Lifemother (O4/O5 only) → a single fixed 'ATK⚔️ HP❤️'.

⚠️ Known issue (CLAUDE.md TODO): the minor "TrainBoss" bosses (Athane/Korin/
Elebor/Quoto/Phalanx/Undying Spirit/Qel/Ajax) currently run through the same
boss_overgrowth_scaled formula as the region bosses, which over-inflates their
HP. Their numbers are emitted anyway (tracked for a formula fix).

Usage:  python3 mt2_emit_boss_stats.py [--in out] [--difficulty Overgrowth] [--write gamedata.js]
"""
import sys, os, re, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mt2_build_outputs as B

ASTRAEL_INTERNAL = 'Boss_SoulSavior_R0_TrainBoss_Defensive'

# Ordered (comment, [(variant_key, internal_or_None)]) groups — mirrors the app's
# VARIANT_OPTIONS. internal=None → resolve via VARIANT_NAMES (region/Lifemother
# variants, shared display name) or by roster display name (battle bosses).
GROUPS = [
    ('Astrael (O1 only; both combats are the same Astrael fight)', [
        ("Mother's Flagellant", ASTRAEL_INTERNAL),
        ("Mother's Hunter",     ASTRAEL_INTERNAL)]),
    ('Lifemother (final boss; single fixed stat)', [
        ('The Corpseflower', None), ('The Swarmhost', None), ('The Undying Bloom', None)]),
    ('Maera Battle', [('Athane the Fallen', None), ('Korin the Judged', None)]),
    ('Maera Boss',   [('Stern Sister', None), ('Sibling Hierarchy', None), ('Eldest Scion', None)]),
    ('Thaddeus Battle', [('Elebor the Unstoppable', None), ('Quoto the Destroyer', None)]),
    ('Thaddeus Boss',   [('Train Chomper', None), ('Thick Skinned', None), ('Insatiable', None)]),
    ('Tivi Battle', [('Phalanx', None), ('The Undying Spirit', None)]),
    ('Tivi Boss',   [('Duplicitous', None), ('Mischevious Child', None), ('Prankster', None)]),
    ('Lylith Battle', [('Qel the Malaiser', None), ('Ajax the Deathbringer', None)]),
    ('Lylith Boss',   [('Plaguebringer', None), ('Energy Vampire', None), ('Inoculation', None)]),
]

PLACEHOLDER = '0⚔️ 0❤️'


def stat(a, h):
    return PLACEHOLDER if a is None or h is None else f'{a}⚔️ {h}❤️'


def value_for(e, diff, total_pct):
    """Return a single string (one applicable order) or a 4-element [O1..O4] list."""
    o = B.compute_orders(e, diff, total_pct)
    present = [n for n in (1, 2, 3, 4, 5) if o.get(f'o{n}a') is not None]
    if present == [1]:
        return stat(o['o1a'], o['o1h'])          # Astrael
    if present == [5]:
        return stat(o['o5a'], o['o5h'])          # Lifemother
    return [stat(o[f'o{n}a'], o[f'o{n}h']) for n in (1, 2, 3, 4)]


def render_block(roster, diff, total_pct):
    by_internal = {e['internal']: e for e in roster}
    by_name = {e['name']: e for e in roster}
    display_to_internal = {v: k for k, v in B.VARIANT_NAMES.items()}

    lines = [
        '// ---- Per-variant stats by visit order ----',
        '// Keyed by variant name. Main-region + minor bosses store',
        "// ['O1','O2','O3','O4'] of 'ATK⚔️ HP❤️'; Astrael (O1) and Lifemother",
        '// (final) store a single fixed string. Generated by',
        '// extraction/mt2_emit_boss_stats.py — do not hand-edit.',
        'const BOSS_STATS = {',
    ]
    missing = []
    for comment, entries in GROUPS:
        lines.append(f'    // {comment}')
        for key, internal in entries:
            internal = internal or display_to_internal.get(key)
            e = by_internal.get(internal) if internal else by_name.get(key)
            if not e:
                missing.append(key)
                val = PLACEHOLDER
            else:
                val = value_for(e, diff, total_pct)
            lines.append(f'    {json.dumps(key)}: {json.dumps(val, ensure_ascii=False)},')
    lines.append('};')
    return '\n'.join(lines), missing


def main():
    argv = sys.argv[1:]
    indir = argv[argv.index('--in') + 1] if '--in' in argv else 'out'
    diff = argv[argv.index('--difficulty') + 1] if '--difficulty' in argv else 'Overgrowth'
    target = argv[argv.index('--write') + 1] if '--write' in argv else None

    roster = json.load(open(os.path.join(indir, 'roster.json')))
    scaling = json.load(open(os.path.join(indir, 'scaling.json')))
    total_pct = B.build_model(scaling)

    block, missing = render_block(roster, diff, total_pct)
    if missing:
        print('WARNING: unresolved variants ->', missing, file=sys.stderr)

    if not target:
        print(block)
        return

    src = open(target).read()
    pat = re.compile(r'(?:^//[^\n]*\n)*const BOSS_STATS = \{.*?\n\};',
                     re.DOTALL | re.MULTILINE)
    src, n = pat.subn(lambda _: block, src, count=1)
    if n != 1:
        sys.exit(f'ERROR: could not locate BOSS_STATS block in {target}')
    open(target, 'w').write(src)
    print(f'Updated {target} ({diff})')


if __name__ == '__main__':
    main()
